# Generated by Django 6.0.6 on 2026-06-05 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('place_type', models.CharField(db_index=True, max_length=60)),
                ('description', models.TextField()),
                ('image_url', models.URLField(max_length=500)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('home_country', models.CharField(blank=True, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('visit_date', models.CharField(blank=True, max_length=20)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='api.attraction')),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='api.visitor')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('account__isnull', False)), fields=('account', 'attraction'), name='unique_account_attraction')],
            },
        ),
    ]
